name: React CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t runcola/myapp:latest .

    - name: Save Docker image
      run: |
        docker save runcola/myapp:latest -o my-react-app.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: react-docker-image
        path: my-react-app.tar

    - name: SSH 접속 후 Docker 실행
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull runcola/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 80:80 runcola/myapp:latest